from datetime import timedelta

ROOM_NAME_MIN_LEN = 1
ROOM_NAME_MAX_LEN = 255

ROOM_DESCRIPTION_MIN_LEN = 1
ROOM_DESCRIPTION_MAX_LEN = 1024

SLOT_TIME_DIFFERENCE = timedelta(hours=1)
SLOT_MIN_TIME = 10
SLOT_MAX_TIME = 19
