from datetime import timedelta

ROOM_NAME_MIN_LEN = 1
ROOM_NAME_MAX_LEN = 255
ROOM_FLOOR_MIN_VALUE = 1
ROOM_CAPACITY_MIN_VALUE = 1

ROOM_DESCRIPTION_MIN_LEN = 1
ROOM_DESCRIPTION_MAX_LEN = 1024

SLOT_TIME_DIFFERENCE = timedelta(hours=1)

SLOT_MIN_TIME = 5  # 10:00 по ЕКБ
SLOT_MAX_TIME = 14  # 19: 00 по ЕКБ

USER_HASHED_PASSWORD_MIN_LEN = 1
USER_HASHED_PASSWORD_MAX_LEN = 255
