"""fix_defaults

Revision ID: 9fbccbeaa598
Revises: 831ecfd56441
Create Date: 2026-06-18 23:30:48.975127

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9fbccbeaa598"
down_revision: str | Sequence[str] | None = "831ecfd56441"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bookings",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "bookings",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
