"""init

Revision ID: f9e5588d9210
Revises:
Create Date: 2026-06-17 01:55:02.763852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import roomslot.models.enums

# revision identifiers, used by Alembic.
revision: str = "f9e5588d9210"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "building",
            roomslot.models.enums.SqlEnum("ГУК", "ИРИТ-РТФ", name="building", native_enum=False),
            nullable=False,
        ),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity >= 1", name=op.f("ck_rooms_capacity_min_val")),
        sa.CheckConstraint("char_length(trim(name)) >= 1", name=op.f("ck_rooms_name_min_len")),
        sa.CheckConstraint(
            "description IS NULL OR char_length(trim(description)) >= 1",
            name=op.f("ck_rooms_description_min_len_or_none"),
        ),
        sa.CheckConstraint("floor >= 1", name=op.f("ck_rooms_floor_min_val")),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_rooms_updated_at_ge_than_created_at")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint("name", "building", "floor", name=op.f("uq_rooms_name_building_floor")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255, collation="utf8mb4_0900_ai_ci"), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            roomslot.models.enums.SqlEnum("user", "admin", name="userrole", native_enum=False),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(trim(email)) >= 1", name=op.f("ck_users_email_min_len")),
        sa.CheckConstraint(
            "char_length(trim(hashed_password)) >= 1", name=op.f("ck_users_hashed_password_min_len")
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_users_updated_at_ge_than_created_at")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("booking_date", sa.Date(), nullable=False),
        sa.Column("slot_start", sa.Time(), nullable=False),
        sa.Column(
            "status",
            roomslot.models.enums.SqlEnum(
                "active", "cancelled", name="bookingstatus", native_enum=False
            ),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "active_slot_key",
            sa.String(length=128),
            sa.Computed(
                "CASE WHEN (status = 'active') "
                "THEN concat(room_id, ':', booking_date, ':', slot_start) "
                "ELSE NULL END",
            ),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status = 'active' AND cancelled_at IS NULL "
            "OR status = 'cancelled' AND cancelled_at IS NOT NULL",
            name=op.f("ck_bookings_booking_state"),
        ),
        sa.CheckConstraint(
            "cancelled_at IS NULL OR cancelled_at >= created_at",
            name=op.f("ck_bookings_cancelled_at_ge_than_created_at"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_bookings_updated_at_ge_than_created_at")
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.id"], name=op.f("fk_bookings_room_id_rooms"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bookings_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint("active_slot_key", name=op.f("uq_bookings_active_slot_key")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bookings")
    op.drop_table("users")
    op.drop_table("rooms")
    # ### end Alembic commands ###
